
[gcp_service_account]
[gcp_service_account]
type = "service_account"
project_id = "vacaciones-ch1"                    # del JSON
private_key_id = "fc81331c9b0330471392fefcc56f6d98b26709fa"               # del JSON
private_key = "-----BEGIN PRIVATE KEY-----\nMIIB...==\n-----END PRIVATE KEY-----\n"
client_email = "vacaciones-ch1@vacaciones-ch1.iam.gserviceaccount.com"  # del JSON
client_id = "104652139210502546713"           # del JSON
token_uri = "https://oauth2.googleapis.com/token"

sheet_url = "https://docs.google.com/spreadsheets/d/1JmMdi_r-igNdc5m1__UtPiBomqXjimLbjbkOddCtQl8/edit?gid=1655081494#gid=1655081494"  # la URL de tu Sheet
admin_password = "panfis182727"                                        # puedes cambiarla
